os:
    - linux

services:
    - docker

language: node_js

node_js:
    - "8.11.1"

jdk:
    - oraclejdk8

cache:
    yarn: true
    directories:
        - $HOME/.m2
        - $HOME/.gradle
        - $HOME/.yarn-cache

env:
    global:
        - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
        - JHIPSTER_INSTALL=$JHIPSTER_TRAVIS/install
        - JHIPSTER_SAMPLES=$TRAVIS_BUILD_DIR/app
        - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    # Install Yarn
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
    - yarn global add yo bower gulp-cli

script:
    - ./gradlew test

