version: '2'
services:
    schwarzschild-app:
        image: schwarzschild
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://schwarzschild-mysql:3306/schwarzschild?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    schwarzschild-mysql:
        extends:
            file: mysql.yml
            service: schwarzschild-mysql
